supporters_filename = ['zhao_xi/view_support/view_support_1.ply',
                       'zhao_xi/view_support/view_support_2.ply',
                       'zhao_xi/view_support/view_support_3.ply',
                       'zhao_xi/view_support/view_support_4.ply',
                       'zhao_xi/view_support/view_support_5.ply',
                       'zhao_xi/view_support/view_support_6.ply',
                       'zhao_xi/view_support/view_support_7.ply',
                       'zhao_xi/view_support/view_support_8.ply',
                       'zhao_xi/view_support/view_support_9.ply',
                       'zhao_xi/view_support/view_support_10.ply',
                       'zhao_xi/view_support/view_support_11.ply',
                       'zhao_xi/view_support/view_support_12.ply',
                       'zhao_xi/view_support/view_support_13.ply',
                       'zhao_xi/view_support/view_support_14.ply',
                       'zhao_xi/view_support/view_support_15.ply',
                       'zhao_xi/view_support/view_support_16.ply',
                       'zhao_xi/view_support/view_support_17.ply',
                       'zhao_xi/view_support/view_support_18.ply',
                       'zhao_xi/view_support/view_support_19.ply',
                       'zhao_xi/view_support/view_support_20.ply']

FX_filename = ['zhao_xi/scraper/FX_1.ply',
               'zhao_xi/scraper/FX_2.ply',
               'zhao_xi/scraper/FX_3.ply',
               'zhao_xi/scraper/FX_4.ply',
               'zhao_xi/scraper/FX_5.ply',
               'zhao_xi/scraper/FX_6.ply',
               'zhao_xi/scraper/FX_7.ply',
               'zhao_xi/scraper/FX_8.ply',
               'zhao_xi/scraper/FX_9.ply',
               'zhao_xi/scraper/FX_10.ply',
               'zhao_xi/scraper/FX_11.ply',
               'zhao_xi/scraper/FX_12.ply',
               'zhao_xi/scraper/FX_13.ply',
               'zhao_xi/scraper/FX_14.ply',
               'zhao_xi/scraper/FX_15.ply',
               'zhao_xi/scraper/FX_16.ply',
               'zhao_xi/scraper/FX_17.ply',
               'zhao_xi/scraper/FX_18.ply',
               'zhao_xi/scraper/FX_19.ply',
               'zhao_xi/scraper/FX_20.ply']

seam_filename = ['zhao_xi/tunnel/coal_wall/up_coal_wall.ply',
                 'zhao_xi/tunnel/coal_wall/coal_wall.ply',
                 'zhao_xi/tunnel/coal_wall/down_coal_wall.ply']

roadway_filename = ['zhao_xi/tunnel/tongfengxiang/tongfengxiang_vertices.vtk',
                    'zhao_xi/tunnel/yunshuxiang/yunshuxiang_vertices.vtk',
                    'zhao_xi/tunnel/work_surface/work_surface_vertices.vtk']

coal_cutter = ['zhao_xi/cmj/CoalCutter.ply']
