supporters_filename = ['zhao_xi/view_support/view_support_1.ply',
                       'zhao_xi/view_support/view_support_2.ply',
                       'zhao_xi/view_support/view_support_3.ply',
                       'zhao_xi/view_support/view_support_4.ply',
                       'zhao_xi/view_support/view_support_5.ply',
                       'zhao_xi/view_support/view_support_6.ply',
                       'zhao_xi/view_support/view_support_7.ply',
                       'zhao_xi/view_support/view_support_8.ply',
                       'zhao_xi/view_support/view_support_9.ply',
                       'zhao_xi/view_support/view_support_10.ply',
                       'zhao_xi/view_support/view_support_11.ply',
                       'zhao_xi/view_support/view_support_12.ply',
                       'zhao_xi/view_support/view_support_13.ply',
                       'zhao_xi/view_support/view_support_14.ply',
                       'zhao_xi/view_support/view_support_15.ply',
                       'zhao_xi/view_support/view_support_16.ply',
                       'zhao_xi/view_support/view_support_17.ply',
                       'zhao_xi/view_support/view_support_18.ply',
                       'zhao_xi/view_support/view_support_19.ply',
                       'zhao_xi/view_support/view_support_20.ply']

FX_filename = ['zhao_xi/scraper/test_FX_1.ply',
               'zhao_xi/scraper/test_FX_2.ply',
               'zhao_xi/scraper/test_FX_3.ply',
               'zhao_xi/scraper/test_FX_4.ply',
               'zhao_xi/scraper/test_FX_5.ply',
               'zhao_xi/scraper/test_FX_6.ply',
               'zhao_xi/scraper/test_FX_7.ply',
               'zhao_xi/scraper/test_FX_8.ply',
               'zhao_xi/scraper/test_FX_9.ply',
               'zhao_xi/scraper/test_FX_10.ply',
               'zhao_xi/scraper/test_FX_11.ply',
               'zhao_xi/scraper/test_FX_12.ply',
               'zhao_xi/scraper/test_FX_13.ply',
               'zhao_xi/scraper/test_FX_14.ply',
               'zhao_xi/scraper/test_FX_15.ply',
               'zhao_xi/scraper/test_FX_16.ply',
               'zhao_xi/scraper/test_FX_17.ply',
               'zhao_xi/scraper/test_FX_18.ply',
               'zhao_xi/scraper/test_FX_19.ply',
               'zhao_xi/scraper/test_FX_20.ply',
               'zhao_xi/scraper/test_FX_21.ply']

workplace_filename = ['zhao_xi/tunnel/coal_wall/up_coal_wall.ply',
                      'zhao_xi/tunnel/coal_wall/coal_wall.ply',
                      'zhao_xi/tunnel/coal_wall/down_coal_wall.ply',
                      'zhao_xi/tunnel/yunshuxiang/yunshuxiang_vertices.vtk',
                      'zhao_xi/tunnel/tongfengxiang/tongfengxiang_vertices.vtk',
                      'zhao_xi/cmj/test_cmj_1.ply']
